# Generated by Django 5.0.6 on 2024-05-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_qna_userlogin_item_cart_order_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='qna',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
