# Generated by Django 5.0.6 on 2024-06-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_refundrequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='state',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
