# Generated by Django 5.0.6 on 2024-06-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_address_order_merchant_uid_order_user_and_more'),
        ('base', '0007_alter_refundrequest_state'),
    ]

    operations = [
    ]
