# Generated by Django 5.0.6 on 2024-06-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_seller_options_alter_seller_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seller',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='username',
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=100, verbose_name='비밀번호'),
        ),
    ]
