# Generated by Django 5.0.6 on 2024-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_merge_20240610_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='merchant_uid',
            field=models.CharField(default='1234', max_length=255),
        ),
    ]
