# Generated by Django 5.0.6 on 2024-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_order_merchant_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='merchant_uid',
            field=models.CharField(default='12345', max_length=255, unique=True),
        ),
    ]
