# Generated by Django 5.0.6 on 2024-06-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_seller_managers_remove_seller_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(default='unique_default_username', max_length=150, unique=True, verbose_name='사용자 이름'),
        ),
    ]
