# Generated by Django 5.0.6 on 2024-06-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_order_merchant_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
