# Generated by Django 5.0.6 on 2024-06-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_seller_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='username',
        ),
    ]
