# Generated by Django 5.0.6 on 2024-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=128, verbose_name='패스워드'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='사용자 이름'),
        ),
    ]
