# Generated by Django 5.0.6 on 2024-06-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_seller_is_superuser_alter_seller_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(default='unique_default_username', max_length=150, unique=True, verbose_name='사용자 이름'),
        ),
    ]
